#!/usr/bin/env python3
"""Generate the appendix cross-tabulation tables (_crosstab_*.tex) from the
released FinRank.jsonl, so they can never drift from the data.

Usage: python make_crosstabs.py --data FinRank.jsonl --out <paper root>/
"""
import argparse, json, collections
from pathlib import Path

SPECS = [
    ("difficulty", "reasoning_type", "difficulty_reasoning", "difficulty", "reasoning type",
     ["Easy", "Medium", "Hard"], ["Qualitative", "Quantitative"], "t",
     "The qualitative-to-quantitative skew is present at every difficulty level."),
    ("passage_type", "reasoning_type", "passagetype_reasoning", "passage type", "reasoning type",
     ["Single-Passage", "Two-Passage", "Multi-Passage"], ["Qualitative", "Quantitative"], "h", ""),
    ("industry", "doc_type", "industry_doctype", "industry", "document type",
     ["Automotive", "Oil & Gas", "Pharmaceuticals"], ["10-K", "10-Q", "Unknown"], "h", ""),
    ("year", "doc_type", "year_doctype", "filing year", "document type",
     [2024, 2025], ["10-K", "10-Q", "Unknown"], "h",
     "The Unknown entry is a record whose raw \\texttt{doc\\_type} names multiple "
     "source documents and cannot be attributed to a single filing."),
    ("industry", "topic", "industry_topic", "industry", "topic",
     ["Automotive", "Oil & Gas", "Pharmaceuticals"],
     ["Accounting", "Company Overview", "Financials", "Footnotes", "Governance",
      "Legal", "Risk", "Shareholder Return"], "h", ""),
]


def latex_escape(v):
    return str(v).replace("&", "\\&")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    recs = [json.loads(l) for l in open(args.data, encoding="utf-8") if l.strip()]

    for rf, cf, name, rlab, clab, rows, cols, pos, extra in SPECS:
        ct = collections.Counter((r.get(rf), r.get(cf)) for r in recs)
        cols_used = [c for c in cols if any(ct.get((rv, c), 0) for rv in rows)]
        lines = [f"% Auto-generated by baselines/make_crosstabs.py from the released JSONL.",
                 f"\\begin{{table}}[{pos}]", "\\centering", "\\small",
                 "\\adjustbox{max width=\\linewidth}{%",
                 "\\begin{tabular}{l" + "r" * (len(cols_used) + 1) + "}", "\\toprule",
                 latex_escape(rlab).capitalize() + " & "
                 + " & ".join(latex_escape(c) for c in cols_used) + " & Row total \\\\", "\\midrule"]
        col_tot = collections.Counter()
        grand = 0
        for rv in rows:
            vals = [ct.get((rv, c), 0) for c in cols_used]
            if not any(vals):
                continue
            for c, v in zip(cols_used, vals):
                col_tot[c] += v
            grand += sum(vals)
            lines.append(latex_escape(rv) + " & "
                         + " & ".join(str(v) if v else "--" for v in vals)
                         + f" & {sum(vals)} \\\\")
        lines += ["\\midrule",
                  "Column total & " + " & ".join(str(col_tot[c]) for c in cols_used)
                  + f" & {grand} \\\\", "\\bottomrule", "\\end{tabular}%", "}",
                  f"\\caption{{Cross-tabulation of {rlab} by {clab} on the canonical "
                  f"normalized labels.{(' ' + extra) if extra else ''}}}",
                  f"\\label{{tab:ct-{name.replace('_','-')}}}", "\\end{table}"]
        Path(args.out, f"_crosstab_{name}.tex").write_text("\n".join(lines) + "\n")
        print(f"_crosstab_{name}.tex: total {grand}")


if __name__ == "__main__":
    main()
